name: Build and Deploy

on:
  push:
    branches:
      - develop
      - project-refactor
      - build-json-the-auto-generate-env-docs
##
jobs:
  calculate_new_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set_tag.outputs.NEW_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  ### Ensure all tags are fetched

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Calculate new tag
        id: set_tag
        run: |
          LAST_TAG=$(git tag -l | grep -E '^[0-9]+\.[0-9]+\.[0-9]+' | sort -V | tail -n 1)
          #LAST_TAG=$(git describe --abbrev=0 --tags)
          export MAJOR=$(echo $LAST_TAG | awk -F'.' '{print $1}')
          export MINOR=$(echo $LAST_TAG | awk -F'.' '{print $2}')
          export PATCH=$(echo $LAST_TAG | awk -F'.' '{print $3}' | awk -F'-' '{print $1}')
          export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD | tr '/' '-') # Convert slashes to dashes if present
          export NEXT_PATCH=$((PATCH + 1))
          export NEW_TAG="$MAJOR.$MINOR.$NEXT_PATCH-$BRANCH_NAME"
          echo "new tag is: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT          
          
  tag_the_commit:
    needs: calculate_new_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          custom_tag: ${{ needs.calculate_new_tag.outputs.tag }}
          #custom_tag: 1.0.46.1-even-v2
          tag_prefix: ""

  build_and_push_image:
    needs: calculate_new_tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure all tags are fetched
        
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: harbor.getapp.sh
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          # path to the Dockerfile
          file: Dockerfile-cts
          context: .
          tags: ${{ secrets.REGISTRY_URL }}/getapp-dev/api:${{ needs.calculate_new_tag.outputs.tag }}
          push: true
          build-args: api_version_tag=${{ needs.calculate_new_tag.outputs.tag }}


  upload-to-server:
    needs: 
      - build_and_push_image
      - calculate_new_tag

    runs-on: ubuntu-latest
    env:
      NEW_VERSION: ${{needs.calculate_new_tag.outputs.tag}}
      IMAGE_URL: ${{ secrets.REGISTRY_URL }}/getapp-dev/api:${{ needs.calculate_new_tag.outputs.tag }}

    steps:
      - name: Print Version from GitHub environment
        run: |
          echo "New version: $NEW_VERSION"
          echo "Image registry url: $IMAGE_URL"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install CLI tool
        run: |
          npm i -g https://github.com/getappsh/cli/releases/latest/download/getapp-cli.tgz
          # print version
          gac -V

      - name: Upload Image to GetApp
        run: |
          # set token
          gac token set $UPLOAD_TOKEN

          # set release
          gac releases set $NEW_VERSION --name "v$NEW_VERSION" --notes "Release v$NEW_VERSION"
          gac releases art $NEW_VERSION docker_image -u $IMAGE_URL -d
          
          echo $?

        env:
          GET_APP_PATH: ${{ secrets.GET_APP_PROJECT_REFACTOR_PATH }}
          UPLOAD_TOKEN: ${{ secrets.PROJECT_REFACTOR_UPLOAD_TOKEN }}  # Add the secret token here

  upload_env_to_s3:
    needs: 
      - calculate_new_tag
    runs-on: ubuntu-latest
    env:
      NEW_VERSION: ${{ needs.calculate_new_tag.outputs.tag }}
      MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
    steps:
      - name: Checkout repo to get files
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install MinIO Client (mc)
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/mc

      - name: Configure mc alias
        run: |
          mc alias set s3 $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --api S3v4

      - name: Update version tag in env.json
        run: |
          jq --arg newTag "$NEW_VERSION" \
            '.version = $newTag' libs/common/src/env/env.json > tmp.json && mv tmp.json libs/common/src/env/env.json

      - name: Upload env.json to MinIO
        run: |
          mc cp libs/common/src/env/env.json s3/getapp-develop-public/env/env-vars.json

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
